version: '3'
services:
  python:
    build: ./python
    container_name: python_3.7
    volumes:
      - ../:/python_app
    tty: true


  #   tty: true
  #   depends_on:
  #       - mysql
  # mysql:
  #   image: mysql:5.7
  #   container_name: mysql_host
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #     - ./mysql/init:/docker-entrypoint-initdb.d
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: game_user
  #     MYSQL_USER: docker
  #     MYSQL_PASSWORD: docker
  #     TZ: 'Asia/Tokyo'
# save SQL data
volumes: 
  mysql_data: